[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/binance-exchange/go-binance"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"
